// System
export const LOADING_DATA = 'LOADING_DATA'
export const LOADING_COMPLETE = 'LOADING_COMPLETE'
export const CLEAR_SESSION = 'CLEAR_SESSION'

// User
export const SET_USER_DATA = 'SET_USER_DATA'

// Data
export const SET_EVENT = 'SET_EVENT'
export const ADD_EVENT = 'ADD_EVENT'
export const DELETE_EVENT = 'DELETE_EVENT'
export const EDIT_EVENT = 'EDIT_EVENT'
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS'
export const ADD_NOTIFICATIONS = 'ADD_NOTIFICATIONS'
export const SET_UNREAD_NOTI = 'SET_UNREAD_NOTI'
