// System
export const LOADING_DATA = 'LOADING_DATA'
export const LOADING_COMPLETE = 'LOADING_COMPLETE'
export const CLEAR_SESSION = 'CLEAR_SESSION'
export const SET_ERROR = 'SET_ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'

// User
export const SET_USER_DATA = 'SET_USER_DATA'

// Friend
export const SET_FRIEND_REQUEST = 'SET_FRIEND_REQUEST'
export const SET_FRIEND_LIST = 'SET_FRIEND_LIST'
export const ACCEPT_FRIEND = 'ACCEPT_FRIEND'
export const DENIED_FRIEND = 'DENIED_FRIEND'
export const SET_SUCCESS  = 'SET_SUCCESS'
export const CLEAR_SUCCESS  = 'CLEAR_SUCCESS'
export const SET_FRIEND_ERROR = 'SET_FRIEND_ERROR'
export const CLEAR_FRIEND_ERROR = 'CLEAR_FRIEND_ERROR'
export const LOADING_FRIEND_DATA = 'LOADING_FRIEND_DATA'
export const LOADING_FRIEND_COMPLETE = 'LOADING_FRIEND_COMPLETE'

// Event
export const SET_EVENT = 'SET_EVENT'
export const ADD_EVENT = 'ADD_EVENT'
export const DELETE_EVENT = 'DELETE_EVENT'
export const EDIT_EVENT = 'EDIT_EVENT'

// Notifications
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS'
export const ADD_NOTIFICATIONS = 'ADD_NOTIFICATIONS'
export const SET_UNREAD_NOTI = 'SET_UNREAD_NOTI'
export const ADD_WILL_NOTI = 'ADD_WILL_NOTI'
export const ADD_NOW_NOTI = 'ADD_NOW_NOTI'
export const ADD_END_NOTI = 'ADD_END_NOTI'
export const READ_NOTI = 'READ_NOTI'
export const TOGGLE_NOTI = 'TOGGLE_NOTI'
export const DELETE_NOTI = 'DELETE_NOTI'
