export const themes = [
    {   //0-primary theme 
        PRIMARY_TEXT_COLOR: 'green',
        BUTTON_TAB_MENU_ONE: '#4A9FFF',
        BUTTON_TAB_MENU_TWO: '#6170D7',
        BUTTON_TAB_MENU_THREE: '#008891',
        BUTTON_TAB_MENU_FOUR: '#20E1D4',
        BUTTON_TAB_MENU_FIVE: '#B9CE8D',
        THEME_NAME: 'Basic',
        COST: 0,
        THEME_THUMBNAIL: 'https://firebasestorage.googleapis.com/v0/b/dtime-44c09.appspot.com/o/7897123.jpg?alt=media',
        BUTTON_TAB_MENU_ONE_IMG: 'https://firebasestorage.googleapis.com/v0/b/dtime-44c09.appspot.com/o/Theme_Icon%2FBasic%2Fcalendar.png?alt=media',
        BUTTON_TAB_MENU_TWO_IMG: 'https://firebasestorage.googleapis.com/v0/b/dtime-44c09.appspot.com/o/Theme_Icon%2FBasic%2Fdiary.png?alt=media',
        BUTTON_TAB_MENU_THREE_IMG: 'https://firebasestorage.googleapis.com/v0/b/dtime-44c09.appspot.com/o/Theme_Icon%2FBasic%2Fstat.png?alt=media',
        BUTTON_TAB_MENU_FOUR_IMG : 'https://firebasestorage.googleapis.com/v0/b/dtime-44c09.appspot.com/o/Theme_Icon%2FBasic%2Fquest.png?alt=media',
        BUTTON_TAB_MENU_FIVE_IMG: 'https://firebasestorage.googleapis.com/v0/b/dtime-44c09.appspot.com/o/Theme_Icon%2FBasic%2Fpet.png?alt=media',
        DIARY_HAPPY_COLOR: '#BEFFB5',
        DIARY_SAD_COLOR: '#A8DEFF',
        DIARY_SOSO_COLOR: '#FBEC98',
        DIARY_ANGRY_COLOR: '#FFDBDB',
    },
    {   //1-pastel theme
        PRIMARY_TEXT_COLOR: 'blue',
        BUTTON_TAB_MENU_ONE: '#A991BA',
        BUTTON_TAB_MENU_TWO: '#DBABDB',
        BUTTON_TAB_MENU_THREE: '#D291BC',
        BUTTON_TAB_MENU_FOUR: '#EDB6D0',
        BUTTON_TAB_MENU_FIVE: '#FACBB4',
        THEME_NAME: 'Pastel',
        COST: 50,
        THEME_THUMBNAIL: 'https://i.pinimg.com/564x/69/29/b2/6929b234c15ad8adf3bdfe8578d1971b.jpg',
        BUTTON_TAB_MENU_ONE_IMG: 'https://firebasestorage.googleapis.com/v0/b/dtime-44c09.appspot.com/o/Theme_Icon%2FPastel%2Fpastel%20calendar.png?alt=media',
        BUTTON_TAB_MENU_TWO_IMG: 'https://firebasestorage.googleapis.com/v0/b/dtime-44c09.appspot.com/o/Theme_Icon%2FPastel%2Fpastel%20diary.png?alt=media',
        BUTTON_TAB_MENU_THREE_IMG: 'https://firebasestorage.googleapis.com/v0/b/dtime-44c09.appspot.com/o/Theme_Icon%2FPastel%2Fpastel%20stat.png?alt=media',
        BUTTON_TAB_MENU_FOUR_IMG : 'https://firebasestorage.googleapis.com/v0/b/dtime-44c09.appspot.com/o/Theme_Icon%2FPastel%2Fpastel%20Q%26A.png?alt=media',       
        BUTTON_TAB_MENU_FIVE_IMG: 'https://firebasestorage.googleapis.com/v0/b/dtime-44c09.appspot.com/o/Theme_Icon%2FPastel%2Fpastel%20pet.png?alt=media',
        DIARY_HAPPY_COLOR: '#EDCFED',
        DIARY_SAD_COLOR: '#F9CDE1',
        DIARY_SOSO_COLOR: '#FBCBC6',
        DIARY_ANGRY_COLOR: '#FBD1C1',
    },
    {   //2-jungle theme
        PRIMARY_TEXT_COLOR: 'red',
        BUTTON_TAB_MENU_ONE: '#A3BFA1',
        BUTTON_TAB_MENU_TWO: '#84A98C',
        BUTTON_TAB_MENU_THREE: '#52796F',
        BUTTON_TAB_MENU_FOUR: '#354F52',
        BUTTON_TAB_MENU_FIVE: '#2F3E46',
        THEME_NAME: 'Jungle',
        COST: 50,
        THEME_THUMBNAIL: 'https://i.pinimg.com/564x/4a/ef/e7/4aefe77bfe3428f42a3af7dcb0f8f497.jpg',
        BUTTON_TAB_MENU_ONE_IMG: 'https://firebasestorage.googleapis.com/v0/b/dtime-44c09.appspot.com/o/Theme_Icon%2FJungle%2Fcalendar.png?alt=media',
        BUTTON_TAB_MENU_TWO_IMG: 'https://firebasestorage.googleapis.com/v0/b/dtime-44c09.appspot.com/o/Theme_Icon%2FJungle%2Fdiary.png?alt=media',
        BUTTON_TAB_MENU_THREE_IMG: 'https://firebasestorage.googleapis.com/v0/b/dtime-44c09.appspot.com/o/Theme_Icon%2FJungle%2Fstat.png?alt=media',
        BUTTON_TAB_MENU_FOUR_IMG : 'https://firebasestorage.googleapis.com/v0/b/dtime-44c09.appspot.com/o/Theme_Icon%2FJungle%2Fquest.png?alt=media',
        BUTTON_TAB_MENU_FIVE_IMG: 'https://firebasestorage.googleapis.com/v0/b/dtime-44c09.appspot.com/o/Theme_Icon%2FJungle%2Fpet.png?alt=media',
        DIARY_HAPPY_COLOR: '#85BC9A',
        DIARY_SAD_COLOR: '#B4D7B2',
        DIARY_SOSO_COLOR: '#A5BBA6',
        DIARY_ANGRY_COLOR: '#92BCB5',
    },
    {   //3-ocean theme
        PRIMARY_TEXT_COLOR: 'yellow',
        BUTTON_TAB_MENU_ONE: '#4798B5',
        BUTTON_TAB_MENU_TWO: '#1C7293',
        BUTTON_TAB_MENU_THREE: '#065A82',
        BUTTON_TAB_MENU_FOUR: '#1B3B6F',
        BUTTON_TAB_MENU_FIVE: '#21295C',
        THEME_NAME: 'Ocean',
        COST: 50,
        THEME_THUMBNAIL: 'https://i.pinimg.com/564x/b1/31/5b/b1315b52c5d85a767a1863d9105f1221.jpg',
        BUTTON_TAB_MENU_ONE_IMG: 'https://firebasestorage.googleapis.com/v0/b/dtime-44c09.appspot.com/o/Theme_Icon%2FOcean%2Fcalendar.png?alt=media',
        BUTTON_TAB_MENU_TWO_IMG: 'https://firebasestorage.googleapis.com/v0/b/dtime-44c09.appspot.com/o/Theme_Icon%2FOcean%2Fdiary.png?alt=media',
        BUTTON_TAB_MENU_THREE_IMG: 'https://firebasestorage.googleapis.com/v0/b/dtime-44c09.appspot.com/o/Theme_Icon%2FOcean%2Fstat.png?alt=media',
        BUTTON_TAB_MENU_FOUR_IMG : 'https://firebasestorage.googleapis.com/v0/b/dtime-44c09.appspot.com/o/Theme_Icon%2FOcean%2Fquest.png?alt=media',
        BUTTON_TAB_MENU_FIVE_IMG: 'https://firebasestorage.googleapis.com/v0/b/dtime-44c09.appspot.com/o/Theme_Icon%2FOcean%2Fpet.png?alt=media',
        DIARY_HAPPY_COLOR: '#7DB8EB',
        DIARY_SAD_COLOR: '#B1CEF1',
        DIARY_SOSO_COLOR: '#A1DEFC',
        DIARY_ANGRY_COLOR: '#B8DAFF',
    },
    {   //4-tropical theme *free*
        PRIMARY_TEXT_COLOR: 'black',
        BUTTON_TAB_MENU_ONE: '#264653',
        BUTTON_TAB_MENU_TWO: '#2A9D8F',
        BUTTON_TAB_MENU_THREE: '#E9C46A',
        BUTTON_TAB_MENU_FOUR: '#F4A261',
        BUTTON_TAB_MENU_FIVE: '#E76F51',
        THEME_NAME: 'Tropical',
        COST: 0,
        THEME_THUMBNAIL: 'https://wallpaperaccess.com/full/1139837.jpg',
        BUTTON_TAB_MENU_ONE_IMG: 'https://firebasestorage.googleapis.com/v0/b/dtime-44c09.appspot.com/o/Theme_Icon%2FBasic%2Fcalendar.png?alt=media',
        BUTTON_TAB_MENU_TWO_IMG: 'https://firebasestorage.googleapis.com/v0/b/dtime-44c09.appspot.com/o/Theme_Icon%2FBasic%2Fdiary.png?alt=media',
        BUTTON_TAB_MENU_THREE_IMG: 'https://firebasestorage.googleapis.com/v0/b/dtime-44c09.appspot.com/o/Theme_Icon%2FBasic%2Fstat.png?alt=media',
        BUTTON_TAB_MENU_FOUR_IMG : 'https://firebasestorage.googleapis.com/v0/b/dtime-44c09.appspot.com/o/Theme_Icon%2FBasic%2Fquest.png?alt=media',
        BUTTON_TAB_MENU_FIVE_IMG: 'https://firebasestorage.googleapis.com/v0/b/dtime-44c09.appspot.com/o/Theme_Icon%2FBasic%2Fpet.png?alt=media',
        DIARY_HAPPY_COLOR: '#EFD595',
        DIARY_SAD_COLOR: '#7EB7C4',
        DIARY_SOSO_COLOR: '#86DFD5',
        DIARY_ANGRY_COLOR: '#F7BC8D',
    }
]